### ISSUE TITLE
which astyle rules are set for Arduino?

### ISSUE THREAD

**Issue by soundanalogous** [arduino/astyle#1]
I'm wondering which [astyle options](http://astyle.sourceforge.net/astyle.html) are set for Arduino (for c++ files and for .ino files via Auto Format). I've dug through the source code and cannot file the astyle options anywhere. It doesn't look like you're using astyle default options for c++ either (4 space indentation, no inline brackets, etc) so I'm assuming they must be specified somewhere.

**Comment by ffissore** [comment]
AStyle options are specified in file `IDE/lib/formatter.conf`. Which version of the IDE are you using? Astyle has been introduced with 1.5.5

**Comment by soundanalogous** [comment]
No wonder why I never found it, I was looking through the Arduino source code rather than in the application directory itself. Thanks for pointing out the location. Super helpful!

**Comment by soundanalogous** [comment]
Guess I wasn't digging far enough... found it here: https://github.com/arduino/Arduino/tree/ide-1.5.x/build/shared/lib.
