### ISSUE TITLE
/usr/lib/jvm/default-java requirement for build

### ISSUE THREAD

**Issue by CRImier** [arduino/astyle#2]
Hi! I was building astyle on a freshly-set system. However, build was failing in the very beginning because /usr/lib/jvm/default-java folder didn't exist, and it wasn't clear from the description. I created a symlink, and it compiled happily. 
Seems like this location might not be necessarily existent or pointing to the preferred JVM. For example, on Debian Wheezy this symlink is provided by 'default-jre-headless' package, which has 'openjdk-6-jre-headless' dependency and I presume this is what gets selected as default JVM, even though there's OpenJDK 7 available in the same release. Should we mention it in the readme or somewhere else? Or is it like 'Java on Linux 101'? =-)

**Comment by ffissore** [comment]
We rely on astyle makefile for building astyle. Our scripts merely help us automate it on linux and mac (on windows we do it manually with visual studio). Please contact astyle support http://astyle.sourceforge.net/
